version: '3.8'
services:
  redis-server:
    image: redis:7.2.5
    container_name: redis_local_docker
    restart: always
    ports:
      - '6379:6379'
    networks:
      - gamestore-network
    volumes: 
      - ./data/redis:/data # Store container data in the project directory

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=localhost:redis_local_docker:6379
    ports:
      - '8082:8081'
    networks:
      - gamestore-network

networks:
  gamestore-network:
    driver: bridge